title: jx0
email: your-email@example.com
description: A blog for software engineering and technical projects I embark on
baseurl: ""
url: "https://jx0.uk"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
